#!/bin/bash
# Installs and uninstalls gpgpassman using git

main () {
    case $1 in
        install)
            read -p "Install gpgpassman to /usr/bin/gpgpassman? Y/N " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Nn]$ ]]; then
                echo "gpgpassman was not installed."
                exit 0
            fi
            git clone https://github.com/simoniz0r/gpgpassman.git /tmp/gpgpassman || { echo "git clone failed; make sure you have git installed and try again later" ; exit 1 ; }
            echo "Moving gpgpassman to /usr/bin/gpgpassman"
            mv /tmp/gpgpassman/gpgpassman.sh /usr/bin/gpgpassman
            echo "Making gpgpassman executable"
            chmod +x /usr/bin/gpgpassman
            echo "Moving gpgpassman icon to /usr/share/icons/gpgpassman.png"
            mv /tmp/gpgpassman/gpgpassman.png /usr/share/icons/gpgpassman.png
            echo "Moving .desktop file to /usr/share/applications/gpgpassman.desktop"
            mv /tmp/gpgpassman/gpgpassman.desktop /usr/share/applications/gpgpassman.desktop
            rm -rf /tmp/gpgpassman
            echo "Install finished!"
            ;;
        uninstall)
            read -p "Uninstall gpgpassman from /usr/bin/gpgpassman? Y/N " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Nn]$ ]]; then
                echo "gpgpassman was not uninstalled."
                exit 0
            fi
            if [ -f "/usr/bin/gpgpassman" ]; then
                rm -f /usr/bin/gpgpassman
                echo "gpgpassman has been removed!"
            else
                echo "/usr/bin/gpgpassman does not exist!"
            fi
            if [ -f "/usr/share/icons/gpgpassman.png" ]; then
                rm -f /usr/share/icons/gpgpassman.png
                echo "gpgpassman.png has been removed!"
            else
                echo "gpgpassman.png does not exist!"
            fi
            if [ -f "/usr/share/applications/gpgpassman.desktop" ]; then
                rm -f /usr/share/applications/gpgpassman.desktop
                echo "gpgpassman.desktop has been removed!"
            else
                echo "gpgpassman.desktop does not exist!"
            fi
            exit 0
            ;;
        help)
            echo "Usage:"
            echo "'sudo ./gpminst install' for installation process"
            echo "'sudo ./gpminst uninstall' for uninstallation process"
            exit 0
            ;;
        *)
            read -p "What would you like to do? install/uninstall "
            echo
            main "$REPLY"
    esac
        
}

programisinstalled () {
  # set to 1 initially
  return=1
  # set to 0 if not found
  type "$1" >/dev/null 2>&1 || { return=0; }
  # return value
}

if [ "$EUID" -ne 0 ]; then
    echo "gpminst install and uninstall must be ran as root!"
    main "help"
    exit 0
fi
programisinstalled "wget"
if [ "$return" = "1" ]; then
    main "$1"
else
    echo "wget is not installed; cannot download gpgpassman."
fi
